import { PAINT } from '../Mark';
import type { MockupItem } from '../types';
import { photo } from './PhotoScene';

export const photoApparel: MockupItem[] = [
	{
		id: 'foto-camiseta-serigrafia',
		title: 'Camiseta blanca con serigrafía frontal',
		category: 'ropa',
		technique: 'Serigrafía 1 tinta',
		material: 'Algodón peinado 180 g',
		note: 'Isologo completo centrado en el pecho, ~24 cm de ancho en talla M.',
		credit: { photographer: 'Mr. Mockup', url: 'https://www.pexels.com/photo/a-blank-white-shirt-12025472/' },
		Scene: photo('/mockups/ropa-camiseta-flatlay.jpg', 'Camiseta blanca flat lay con el isologo serigrafiado en el pecho', [
			{
				kind: 'isologo',
				x: 49,
				y: 45,
				w: 26,
				mono: PAINT.navy,
				blend: 'multiply',
				opacity: 0.88,
				shade: 'linear-gradient(135deg, rgba(255,255,255,0.18), rgba(0,0,0,0.1))',
			},
		]),
	},
	{
		id: 'foto-camiseta-bordado',
		title: 'Camiseta en percha con bordado de pecho',
		category: 'ropa',
		technique: 'Bordado plano',
		material: 'Algodón 100% jersey',
		note: 'Símbolo bordado de ~8 cm en el pecho izquierdo, tamaño real de prenda terminada.',
		credit: { photographer: 'Marina Podrez', url: 'https://www.pexels.com/photo/white-t-shirt-hanging-on-a-rack-11671964/' },
		Scene: photo('/mockups/ropa-camiseta-percha.jpg', 'Camiseta blanca en percha con el símbolo bordado en el pecho', []),
	},
	{
		id: 'foto-hoodie-estampado',
		title: 'Hoodie blanco con estampado frontal',
		category: 'ropa',
		technique: 'Serigrafía 1 tinta',
		material: 'Felpa 320 g',
		note: 'Estampado de ~26 cm centrado en el pecho, tamaño típico de un print frontal grande.',
		credit: { photographer: 'MART PRODUCTION', url: 'https://www.pexels.com/photo/a-bearded-man-wearing-a-white-hoodie-8217416/' },
		Scene: photo('/mockups/ropa-hoodie-blanco.jpg', 'Hoodie blanco con el isologo estampado en el pecho', []),
	},
	{
		id: 'foto-gorra-bordada',
		title: 'Gorra trucker con símbolo bordado',
		category: 'ropa',
		technique: 'Bordado plano',
		material: 'Panel frontal de algodón',
		note: 'Símbolo bordado que ocupa ~45% del ancho del panel frontal.',
		credit: { photographer: 'MART PRODUCTION', url: 'https://www.pexels.com/photo/a-woman-wearing-a-cap-9558708/' },
		Scene: photo('/mockups/ropa-gorra-blanca.jpg', 'Gorra blanca y negra con el símbolo bordado en el panel frontal', []),
	},
	{
		id: 'foto-etiqueta-cuello',
		title: 'Etiqueta interior de cuello',
		category: 'ropa',
		technique: 'Impresión textil',
		material: 'Cinta de algodón',
		note: 'Etiqueta interior típica: símbolo pequeño resistente a lavado, cosido en el cuello.',
		credit: { photographer: 'Atlantic Ambience', url: 'https://www.pexels.com/photo/blue-denim-jeans-with-white-tag-12944657/' },
		Scene: photo('/mockups/ropa-etiqueta-cuello.jpg', 'Etiqueta interior en blanco con el símbolo impreso', []),
	},
	{
		id: 'foto-colgante-lino',
		title: 'Colgante de precio sobre lino',
		category: 'ropa',
		technique: 'Hot stamping dorado',
		material: 'Cartulina 350 g',
		note: 'Colgante atado con hilo de algodón; foil dorado sobre cartulina clara.',
		credit: { photographer: 'Andrzej Gdula', url: 'https://www.pexels.com/photo/blank-paper-tag-on-textile-11485130/' },
		Scene: photo('/mockups/ropa-colgante-lino.jpg', 'Colgante en blanco sobre tela de lino con el isologo en foil dorado', []),
	},
	{
		id: 'foto-chaqueta-cuero',
		title: 'Chaqueta de cuero con símbolo en foil',
		category: 'ropa',
		technique: 'Hot stamping dorado',
		material: 'Cuero napa negro',
		note: 'Símbolo estampado en foil dorado de ~6 cm sobre el panel de pecho.',
		credit: { photographer: 'Abfilms Studio', url: 'https://www.pexels.com/photo/a-man-in-black-leather-jacket-15345396/' },
		Scene: photo('/mockups/ropa-chaqueta-cuero.jpg', 'Chaqueta de cuero negra con el símbolo en foil dorado', []),
	},
];
