import type { MockupItem } from '../types';
import { photo } from './PhotoScene';

export const photoHome: MockupItem[] = [
	{
		id: 'foto-taza-blanca',
		title: 'Taza de cerámica blanca',
		category: 'hogar',
		technique: 'Serigrafía cerámica 1 tinta',
		material: 'Cerámica esmaltada blanca',
		note: 'El isologo va más angosto que el cuerpo de la taza para que la curvatura no lo deforme.',
		credit: { photographer: 'BlushPink Studio', url: 'https://www.pexels.com/photo/close-up-photo-of-white-ceramic-mug-13360742/' },
		Scene: photo('/mockups/hog-taza-blanca.jpg', 'Taza de cerámica blanca con el isologo de Victoria de Dios', []),
	},
	{
		id: 'foto-taza-negra',
		title: 'Taza mate negra',
		category: 'hogar',
		technique: 'Hot stamping dorado',
		material: 'Cerámica mate negra',
		note: 'Dorado sobre negro mate: la combinación de mayor percepción de valor para menaje de regalo.',
		credit: { photographer: 'Engin Akyurt', url: 'https://www.pexels.com/photo/a-white-mug-beside-a-tea-bag-on-a-glossy-surface-10965869/' },
		Scene: photo('/mockups/hog-taza-negra.jpg', 'Taza mate negra con el isologo dorado', []),
	},
	{
		id: 'foto-tomatodo',
		title: 'Tomatodo de acero inoxidable',
		category: 'hogar',
		technique: 'Grabado láser',
		material: 'Acero inoxidable cepillado',
		note: 'Grabado láser directo sobre el metal: sin tintas, resiste lavavajillas y uso diario.',
		credit: { photographer: 'Tima Miroshnichenko', url: 'https://www.pexels.com/photo/fresh-lemon-fruit-beside-a-stainless-jug-7879967/' },
		Scene: photo('/mockups/hog-tomatodo.jpg', 'Tomatodo de acero inoxidable con el isologo grabado', []),
	},
	{
		id: 'foto-vela',
		title: 'Vela aromática en frasco de vidrio',
		category: 'hogar',
		technique: 'Etiqueta impresa',
		material: 'Frasco de vidrio con etiqueta blanca',
		note: 'Etiqueta plana sobre vidrio: la aplicación más económica para línea de fragancias de hogar.',
		credit: { photographer: 'KATRIN BOLOVTSOVA', url: 'https://www.pexels.com/photo/burning-candle-on-a-wooden-surface-6311868/' },
		Scene: photo('/mockups/hog-vela.jpg', 'Vela aromática con la etiqueta de Victoria de Dios', []),
	},
	{
		id: 'foto-cojin',
		title: 'Cojín decorativo bordado',
		category: 'hogar',
		technique: 'Bordado dos hilos',
		material: 'Lino color hueso',
		note: 'Bordado en dos tonos de hilo: el acabado textil de mayor percepción de valor.',
		credit: { photographer: 'KATRIN BOLOVTSOVA', url: 'https://www.pexels.com/photo/throw-pillow-on-a-brown-leather-chair-6312042/' },
		Scene: photo('/mockups/hog-cojin.jpg', 'Cojín de lino hueso con el isologo bordado', []),
	},
	{
		id: 'foto-toallas',
		title: 'Toallas de algodón dobladas',
		category: 'hogar',
		technique: 'Bordado',
		material: 'Algodón rizo beige',
		note: 'Un monograma pequeño en la orilla doblada, como en la ropa de baño de hotelería de lujo.',
		credit: { photographer: 'kaboompics.com', url: 'https://www.pexels.com/photo/stack-of-light-beige-towels-on-white-stool-4210372/' },
		Scene: photo('/mockups/hog-toallas.jpg', 'Toallas de algodón beige con el símbolo bordado en la orilla', []),
	},
	{
		id: 'foto-difusor',
		title: 'Difusor de aromas con varillas',
		category: 'hogar',
		technique: 'Etiqueta impresa',
		material: 'Frasco de vidrio ámbar con etiqueta blanca',
		note: 'Misma etiqueta blanca de la línea de vela: coherencia entre las piezas de fragancia de hogar.',
		credit: { photographer: 'Alesia Kozik', url: 'https://www.pexels.com/photo/close-up-of-a-glass-container-with-incense-sticks-7795650/' },
		Scene: photo('/mockups/hog-difusor.jpg', 'Difusor de aromas con la etiqueta de Victoria de Dios', []),
	},
	{
		id: 'foto-bata',
		title: 'Bata de baño en waffle blanco',
		category: 'hogar',
		technique: 'Bordado',
		material: 'Algodón waffle blanco',
		note: 'Símbolo bordado sobre el pecho, en tono dorado sobre blanco, como en las batas de un hotel boutique.',
		credit: { photographer: 'Sami Abdullah', url: 'https://www.pexels.com/photo/a-bathrobe-hanging-on-the-rack-10520144/' },
		Scene: photo('/mockups/hog-bata.jpg', 'Bata de baño blanca con el símbolo bordado en el pecho', []),
	},
];
